//! Rendered hardware, for the parts that are photographed rather than drawn.
//!
//! Only the boost, atten and bandwidth knobs and the mounting screws come from
//! images; everything else on the panel is drawn with paths in `style.rs`. The
//! knobs are generated by `assetgen` from parametric geometry under one
//! lighting rig, so a knob's highlight stays where the light is when it turns.
//!
//! An image belongs to the canvas that uploaded it, and a second instance of
//! the plugin gets a second canvas, so each widget uploads and caches its own
//! rather than sharing one through a global.

use nih_plug_vizia::vizia::prelude::Canvas;
use nih_plug_vizia::vizia::vg;
use std::cell::Cell;

/// The renders, embedded so the plugin stays a single file.
pub const KNOB_LARGE: &[u8] = include_bytes!("../../assets/gen/knob_large.png");

/// The four mounting screws, each photographed already driven to its own
/// angle. Nothing is rotated here: a screw sits where it was tightened, and
/// turning one image would carry its lighting round with it.
pub const SCREWS: [&[u8]; 4] = [
    include_bytes!("../../assets/screw_1.png"),
    include_bytes!("../../assets/screw_2.png"),
    include_bytes!("../../assets/screw_3.png"),
    include_bytes!("../../assets/screw_4.png"),
];

/// How much of the square render the knob body fills: its radius divided by
/// the framed half-extent, as reported by `assetgen --nominal`. The frame is
/// wider than the body so the skirt's overhang and its shadow survive.
pub const KNOB_LARGE_SPAN: f32 = 0.9852;

/// How wide the knob body is drawn, in multiples of the layout radius the
/// panel asks for. The faceplate's engraved scales were laid out around
/// hardware that overhangs its nominal circle, so a knob drawn at exactly its
/// radius sits marooned inside its own dial.
pub const KNOB_LARGE_DRAW: f32 = 2.50;

/// How many frames the knob's filmstrip holds, spanning the full `SWEEP`. A
/// turning knob cannot be drawn by rotating one image: that turns its lighting
/// with it, so the highlight travels round the knob instead of staying where
/// the panel light is. Each frame is rendered separately with the light fixed,
/// and drawing picks one.
pub const KNOB_FRAMES: usize = 48;

/// Every render is square, centred on the shaft, with the indicator at twelve
/// o'clock. That leaves nothing to calibrate per image: no rest angle, and one
/// pivot for everything.
pub const CENTRE: (f32, f32) = (0.5, 0.5);

/// Where and how large to draw a photograph, and about which point to turn
/// it. Grouped rather than passed as a row of bare numbers, because they are
/// all lengths and angles and easy to transpose.
#[derive(Clone, Copy)]
pub struct Placement {
    /// Where the shaft goes.
    pub x: f32,
    pub y: f32,
    /// Drawn height; the renders are square, so this is the width too.
    pub height: f32,
    /// Clockwise from twelve o'clock.
    pub degrees: f32,
    /// The shaft's position within the render.
    pub pivot: (f32, f32),
}

impl Placement {
    pub fn new(x: f32, y: f32, height: f32, degrees: f32, pivot: (f32, f32)) -> Self {
        Self { x, y, height, degrees, pivot }
    }
}

/// A lazily uploaded image. The canvas is only reachable from `draw`, so the
/// upload happens on the first frame and the id is kept from then on.
#[derive(Default)]
pub struct Sprite {
    id: Cell<Option<vg::ImageId>>,
}

impl Sprite {
    pub const fn new() -> Self {
        Self {
            id: Cell::new(None),
        }
    }

    fn id(&self, canvas: &mut Canvas, bytes: &[u8]) -> Option<vg::ImageId> {
        if let Some(id) = self.id.get() {
            return Some(id);
        }
        // Mipmaps keep the knobs from crawling when the window is scaled down.
        let flags = vg::ImageFlags::GENERATE_MIPMAPS;
        match canvas.load_image_mem(bytes, flags) {
            Ok(id) => {
                self.id.set(Some(id));
                Some(id)
            }
            Err(_) => None,
        }
    }

    /// Draws one frame of a vertical filmstrip with its shaft on a point.
    ///
    /// No rotation is applied: the frame was rendered at the angle wanted, so
    /// its highlights and shadow sit where the panel light put them.
    pub fn draw_frame(
        &self,
        canvas: &mut Canvas,
        bytes: &[u8],
        at: Placement,
        frame: usize,
        frames: usize,
    ) {
        let Some(id) = self.id(canvas, bytes) else {
            return;
        };
        let Ok((iw, ih)) = canvas.image_size(id) else {
            return;
        };
        let strip = frames.max(1);
        let frame = frame.min(strip - 1);
        let cell = ih as f32 / strip as f32;
        let scale = at.height / cell;
        let (w, h) = (iw as f32 * scale, cell * scale);

        canvas.save();
        canvas.translate(at.x - w * at.pivot.0, at.y - h * at.pivot.1);
        // The paint covers the whole strip, shifted so the wanted frame lands
        // on the rectangle being filled; the path clips away the rest.
        let mut path = vg::Path::new();
        path.rect(0.0, 0.0, w, h);
        canvas.fill_path(
            &path,
            &vg::Paint::image(
                id,
                0.0,
                -(frame as f32) * h,
                w,
                h * strip as f32,
                0.0,
                1.0,
            ),
        );
        canvas.restore();
    }

    /// Draws the render with its shaft on a point, turned by `degrees`.
    pub fn draw(&self, canvas: &mut Canvas, bytes: &[u8], at: Placement) {
        let Some(id) = self.id(canvas, bytes) else {
            return;
        };
        let Ok((iw, ih)) = canvas.image_size(id) else {
            return;
        };
        // Scale to the requested height, keeping the render's proportions.
        let scale = at.height / ih as f32;
        let (w, h) = (iw as f32 * scale, ih as f32 * scale);

        canvas.save();
        canvas.translate(at.x, at.y);
        canvas.rotate(at.degrees.to_radians());
        canvas.translate(-w * at.pivot.0, -h * at.pivot.1);
        let mut path = vg::Path::new();
        path.rect(0.0, 0.0, w, h);
        canvas.fill_path(&path, &vg::Paint::image(id, 0.0, 0.0, w, h, 0.0, 1.0));
        canvas.restore();
    }

}
